# Generated by Django 4.1.3 on 2022-12-21 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizacaoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_atualizacao',
            },
        ),
        migrations.CreateModel(
            name='FootballMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hometeam', models.CharField(max_length=50)),
                ('awayteam', models.CharField(max_length=50)),
                ('fthg', models.IntegerField()),
                ('ftag', models.IntegerField()),
                ('hthg', models.IntegerField()),
                ('htag', models.IntegerField()),
                ('htr', models.CharField(max_length=1)),
                ('ftr', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'app_football_matches',
            },
        ),
        migrations.CreateModel(
            name='OddsProbEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Competição', models.CharField(max_length=50)),
                ('Evento', models.CharField(max_length=50)),
                ('Data', models.CharField(max_length=20)),
                ('Hora', models.CharField(max_length=10)),
                ('Casa', models.CharField(max_length=30)),
                ('Fora', models.CharField(max_length=30)),
                ('Mercado', models.CharField(max_length=25)),
                ('Entrada', models.CharField(max_length=25)),
                ('Odd', models.CharField(max_length=10)),
                ('Probabilidade', models.CharField(max_length=10)),
                ('EV', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'app_odds_prob_ev',
            },
        ),
        migrations.CreateModel(
            name='TarefasAgendadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(max_length=20)),
                ('tempo', models.CharField(max_length=6)),
                ('descricao', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'app_tarefas_agendadas',
            },
        ),
    ]
