# Generated by Django 4.1.3 on 2022-12-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OddsProbEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Competição', models.CharField(max_length=50)),
                ('Evento', models.CharField(max_length=50)),
                ('Data', models.CharField(max_length=20)),
                ('Hora', models.CharField(max_length=10)),
                ('Casa', models.CharField(max_length=30)),
                ('Fora', models.CharField(max_length=30)),
                ('Mercado', models.CharField(max_length=25)),
                ('Entrada', models.CharField(max_length=25)),
                ('Odd', models.CharField(max_length=10)),
                ('Probabilidade', models.CharField(max_length=10)),
                ('EV', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'app_odds_prob_ev',
            },
        ),
    ]
