# Generated by Django 4.1.3 on 2022-12-12 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizacaoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_atualizacao',
            },
        ),
    ]
