# Generated by Django 4.1.3 on 2022-12-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_atualizacaoapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaoapp',
            name='texto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
