# Generated by Django 4.1.3 on 2022-12-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0003_odds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odds',
            old_name='seleção',
            new_name='selecao',
        ),
    ]
